---
# Central project entity. It pulls general templates and basic jobs.
# functional-jobs, metal-jobs and acceptance-jobs are being
# merged with this entity into singe one.
- project:
    templates:
      - check-requirements
      - openstack-python3-jobs
      - openstacksdk-functional-tips
      - openstacksdk-tox-tips
      - os-client-config-tox-tips
      - osc-tox-unit-tips
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-py312
        - opendev-buildset-registry
        - nodepool-build-image-siblings:
            voting: false
        - dib-nodepool-functional-openstack-ubuntu-noble-src:
            voting: false
        - openstacksdk-functional-devstack
        - openstacksdk-functional-devstack-networking
        - openstacksdk-functional-devstack-networking-ext
        - openstacksdk-functional-devstack-magnum:
            voting: false
        - openstacksdk-functional-devstack-manila
        # TODO(stephenfin): We can make this voting again once [1] merges
        # [1] https://review.opendev.org/c/openstack/masakari/+/949153
        - openstacksdk-functional-devstack-masakari:
            voting: false
        - openstacksdk-functional-devstack-ironic:
            voting: false
        - osc-functional-devstack-tips:
            voting: false
        - ansible-collections-openstack-functional-devstack:
            voting: false
    gate:
      jobs:
        - opendev-buildset-registry
        - openstacksdk-functional-devstack
        - openstacksdk-functional-devstack-networking
        - openstacksdk-functional-devstack-networking-ext
