---
# Central project entity. It pulls general templates and basic jobs.
# functional-jobs, metal-jobs and acceptance-jobs are being
# merged with this entity into singe one.
- project:
    templates:
      - check-requirements
      - openstack-python3-jobs
      - openstacksdk-functional-tips
      - openstacksdk-tox-tips
      - os-client-config-tox-tips
      - osc-tox-unit-tips
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-py312
        - opendev-buildset-registry
        - nodepool-build-image-siblings:
            voting: false
        - openstacksdk-functional-devstack
        - openstacksdk-functional-devstack-networking
        - openstacksdk-functional-devstack-networking-ext
        - openstacksdk-functional-devstack-magnum:
            voting: false
        - openstacksdk-functional-devstack-manila
        - openstacksdk-functional-devstack-masakari
        # TODO(stephenfin): Make this voting once we get to the bottom of the
        # 2 failures
        - openstacksdk-functional-devstack-ironic:
            voting: false
        - osc-functional-devstack-tips:
            voting: false
        - ansible-collections-openstack-functional-devstack:
            voting: false
    gate:
      jobs:
        - opendev-buildset-registry
        - openstacksdk-functional-devstack
        - openstacksdk-functional-devstack-networking
        - openstacksdk-functional-devstack-networking-ext
        # TODO(stephenfin): Per above
        # - openstacksdk-functional-devstack-ironic
